name: pytorch_182_LTS
channels:
  - pytorch-lts
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
dependencies:
  - blas=2.112=mkl
  - blas-devel=3.9.0=12_win64_mkl
  - ca-certificates=2021.10.8=h5b45459_0
  - certifi=2021.5.30=py36ha15d459_0
  - console_shortcut=0.1.1=py36_1
  - cudatoolkit=11.1.1=heb2d755_9
  - dataclasses=0.8=pyh787bdff_2
  - intel-openmp=2021.4.0=h57928b3_3556
  - libblas=3.9.0=12_win64_mkl
  - libcblas=3.9.0=12_win64_mkl
  - liblapack=3.9.0=12_win64_mkl
  - liblapacke=3.9.0=12_win64_mkl
  - libsodium=1.0.18=h8d14728_1
  - libuv=1.42.0=h8ffe710_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mkl=2021.4.0=h0e2418a_729
  - mkl-devel=2021.4.0=h57928b3_730
  - mkl-include=2021.4.0=h0e2418a_729
  - msys2-conda-epoch=20160418=1
  - ninja=1.10.2=h2d74725_1
  - numpy=1.19.5=py36h4b40d73_2
  - openssl=3.0.0=h8ffe710_2
  - pip=21.3.1=pyhd8ed1ab_0
  - python=3.6.13=h39d44d4_2_cpython
  - python_abi=3.6=2_cp36m
  - pytorch=1.8.2=py3.6_cuda11.1_cudnn8_0
  - setuptools=58.0.4=py36ha15d459_2
  - tbb=2021.4.0=h2d74725_1
  - torchaudio=0.8.2=py36
  - typing_extensions=4.0.0=pyha770c72_0
  - ucrt=10.0.20348.0=h57928b3_0
  - vc=14.2=hb210afc_5
  - vs2015_runtime=14.29.30037=h902a5da_5
  - wheel=0.37.0=pyhd8ed1ab_1
  - pip:
    - absl-py==1.0.0
    - argon2-cffi==21.1.0
    - async-generator==1.10
    - attrs==21.2.0
    - backcall==0.2.0
    - cachetools==4.2.4
    - cffi==1.15.0
    - charset-normalizer==2.0.7
    - colorama==0.4.4
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - grpcio==1.42.0
    - idna==3.3
    - importlib-metadata==4.8.2
    - ipykernel==5.5.6
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jedi==0.18.1
    - joblib==1.1.0
    - jsonschema==4.0.0
    - jupyter==1.0.0
    - jupyter-client==7.0.6
    - jupyter-console==6.4.0
    - jupyter-core==4.9.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.2
    - markdown==3.3.6
    - nbclient==0.5.9
    - nbconvert==6.0.7
    - nest-asyncio==1.5.1
    - notebook==6.4.6
    - oauthlib==3.1.1
    - pandas==1.1.5
    - parso==0.8.2
    - pillow==8.4.0
    - prometheus-client==0.12.0
    - prompt-toolkit==3.0.22
    - protobuf==3.19.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pyrsistent==0.18.0
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pywin32==302
    - pywinpty==1.1.6
    - qtconsole==5.2.0
    - qtpy==1.11.2
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scikit-learn==0.24.2
    - scipy==1.5.4
    - send2trash==1.8.0
    - six==1.16.0
    - sklearn==0.0
    - tb-nightly==2.8.0a20211117
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - terminado==0.12.1
    - threadpoolctl==3.0.0
    - torchvision==0.9.1+cu111
    - tqdm==4.62.3
    - urllib3==1.26.7
    - webencodings==0.5.1
    - werkzeug==2.0.2
    - widgetsnbextension==3.5.2
    - zipp==3.6.0
prefix: E:\File_coding\Anaconda\envs\pytorch_182_LTS